plugins {
    id 'dev.architectury.loom' version '1.17.+' apply false
    id 'architectury-plugin' version '3.5-SNAPSHOT'
    id 'com.gradleup.shadow' version '9.4.3' apply false
    id 'me.modmuss50.mod-publish-plugin' version '1.+' apply false
}

println('Java: ' + System.getProperty('java.version') + ' JVM: ' + System.getProperty('java.vm.version') + '(' + System.getProperty('java.vendor') + ') Arch: ' + System.getProperty('os.arch'))

architectury {
    minecraft = minecraft_version
}

allprojects {
    group = 'com.alrex'
    version = mod_version
}

subprojects {
    pluginManager.with {
        apply 'java'
        apply 'eclipse'
        apply 'idea'
        apply 'dev.architectury.loom'
        apply 'architectury-plugin'
        apply 'me.modmuss50.mod-publish-plugin'
    }
    base { archivesName = "ParCool-${minecraft_version}-${project.name}" }

    repositories {}

    loom { silentMojangMappingsLicense() }

    dependencies {
        minecraft "net.minecraft:minecraft:$minecraft_version"
        mappings loom.officialMojangMappings()

        compileOnly 'com.google.code.findbugs:jsr305:3.0.2'
    }

    compileJava.options.encoding("UTF-8")
    compileTestJava.options.encoding("UTF-8")
    java {
        toolchain.languageVersion = JavaLanguageVersion.of(17)
        withSourcesJar()
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    tasks.withType(JavaCompile).configureEach { it.options.release = 17 }
}