org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# supported minimum Minecraft version
minecraft_version=1.19.2
minecraft_version_range=[1.19.2,)

mod_version=3.4.3.3
# ALPHA, BETA, STABLE
release_type=STABLE
architectury_api_version=6.6.92

forge_version_range=[43.3,)
forge_loader_version_range=[43,)
forge_version=43.5.2
fabric_loader_version=0.19.3
fabric_api_version=0.77.0+1.19.2
