org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
# --- Mod Info ---
mod_id=parcool
mod_version=4.0.0.1
# ALPHA, BETA, STABLE
release_type=ALPHA
# --- Game Environment ---
# supported minimum Minecraft version
minecraft_version=1.19.2
minecraft_version_range=[1.19.2,)
forge_version=43.5.0
forge_version_range=[43.3,)
loader_version_range=[43,)
# --- External Dependencies ---
jei_version=11.8.1.1034
# Note : Incompatible with curios on 1.19.2 / Curious seem to need old version of Forge, but ParCool need at least 43.3
curios_version=1.19.2-5.1.6.4
curios_version_range=[5.1.6.4,)
betterthirdperson_file_id=4177088
betterthirdperson_version_range=[1.9.0,)
shouldersurfing_file_id=7720588
shouldersurfing_version_range=[1.19.2-4.22.1,)
feathers_file_id=4573576
feathers_version_range=[1.1.2,)
epicfight_file_id=5593321
epicfight_version_range=[19.5.26,)
