# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# supported minimum Minecraft version
minecraft_version=1.19.2
minecraft_version_range=[1.19.2,)
mod_version=3.4.3.3
# ALPHA, BETA, STABLE
release_type=STABLE
forge_version_range=[43.3,)
loader_version_range=[43,)
forge_version=43.5.0
jei_version=11.8.1.1034
# Note : Incompatible with curios on 1.19.2 / Curious seem to need old version of Forge, but ParCool need at least 43.3
curios_version=1.19.2-5.1.6.4
betterthirdperson_file_id=4177088
shouldersurfing_file_id=6496608
feathers_file_id=4573576
epicfight_file_id=5132281
