loom.platform=forge
jei_version=11.8.1.1034
# Note : Incompatible with curios on 1.19.2 / Curious seem to need old version of Forge, but ParCool need at least 43.3
curios_version=1.19.2-5.1.6.4
betterthirdperson_file_id=4177088
shouldersurfing_file_id=7720588
feathers_file_id=4573576
epicfight_file_id=5593321
